### ISSUE TITLE
A code review on portfolio setup desktop version

### ISSUE THREAD

**Issue by dlwub** [canon20paul/My-Portfolio-setup-Desktop-version#11]
You leave many lines of empty lines in your code. 
https://github.com/canon20paul/My-Portfolio-setup-Desktop-version/blob/main/index.js#L10-L25
I think it would be better if you avoid unnecessary empty lines.
Further, it would be better to avoid unused (commented lines of code).
https://github.com/canon20paul/My-Portfolio-setup-Desktop-version/blob/main/index.js#L43-L49
That keeps your code source clean.

**Comment by canon20paul** [comment]
Thank u so much
